name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_cli:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
    - uses: actions/checkout@v5
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies
      run: sudo apt install libasound2-dev

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test

    - name: Clippy
      run: cargo clippy --all-features -- --deny=warnings

    - name: Format
      run: cargo fmt -- --check

  build_pico:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pico

    steps:
    - uses: actions/checkout@v5
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: thumbv6m-none-eabi

    - name: Install flip-link
      run: cargo install flip-link

    - name: Build
      run: cargo build

    - name: Clippy
      run: cargo clippy --all-features -- --deny=warnings

    - name: Format
      run: cargo fmt -- --check
